#!/usr/bin/env python3
"""
Quick deployment setup script for TPC Portal
Helps you set up online database connection and deploy to Railway/Render

Usage: python setup_deployment.py
"""

import os
import sys
from pathlib import Path


def setup_env_file():
    """Create .env file with user inputs"""
    print("\n" + "="*60)
    print("TPC Portal - Online Database Setup")
    print("="*60 + "\n")
    
    env_file = Path(".env")
    
    if env_file.exists():
        response = input(".env file already exists. Overwrite? (y/n): ").lower()
        if response != 'y':
            print("Keeping existing .env file")
            return
    
    print("\nLet's set up your online database!\n")
    
    # Get database URL
    print("1. PostgreSQL Connection String")
    print("   From Railway: Copy 'DATABASE_URL' from project variables")
    print("   From Render: Copy 'External Database URL' from dashboard")
    db_url = input("\nEnter DATABASE_URL: ").strip()
    
    if not db_url.startswith('postgresql://'):
        print("❌ Invalid database URL. Must start with 'postgresql://'")
        sys.exit(1)
    
    # Get secret key
    print("\n2. SECRET_KEY for session encryption")
    print("   (Generate random string, e.g., 'abc123xyz789')")
    secret_key = input("Enter SECRET_KEY: ").strip()
    
    if len(secret_key) < 10:
        print("⚠️  Warning: SECRET_KEY should be at least 10 characters")
    
    # Choose environment
    print("\n3. Environment")
    env = input("development or production? [production]: ").strip().lower() or "production"
    
    if env not in ['development', 'production']:
        env = 'production'
    
    # Write .env file
    env_content = f"""# Generated by setup_deployment.py
DATABASE_URL={db_url}
SECRET_KEY={secret_key}
FLASK_ENV={env}
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ .env file created successfully!")
    print(f"   Environment: {env}")
    print("   Database: PostgreSQL (online)")


def install_dependencies():
    """Install required packages"""
    print("\n" + "-"*60)
    print("Installing dependencies...")
    print("-"*60 + "\n")
    
    os.system("pip install -r requirements.txt")
    print("✅ Dependencies installed!")


def run_migrations():
    """Run database migrations"""
    print("\n" + "-"*60)
    print("Running database migrations...")
    print("-"*60 + "\n")
    
    os.system("flask db upgrade")
    print("✅ Migrations completed!")


def main():
    """Main setup flow"""
    print("\nTPC Portal - Deployment Setup Guide\n")
    
    print("This script will help you:")
    print("  1. Create .env file with online database credentials")
    print("  2. Install all required packages")
    print("  3. Set up database schema\n")
    
    proceed = input("Continue? (y/n): ").lower()
    if proceed != 'y':
        print("Cancelled.")
        sys.exit(0)
    
    # Step 1: Environment
    setup_env_file()
    
    # Step 2: Dependencies
    response = input("\nInstall/update dependencies? (y/n): ").lower()
    if response == 'y':
        install_dependencies()
    
    # Step 3: Migrations
    response = input("\nRun database migrations? (y/n): ").lower()
    if response == 'y':
        run_migrations()
    
    print("\n" + "="*60)
    print("✅ SETUP COMPLETE!")
    print("="*60)
    print("\nNext steps:")
    print("  1. Verify .env file has correct DATABASE_URL")
    print("  2. Test locally: python run.py")
    print("  3. Deploy to Railway/Render by connecting your GitHub repo")
    print("  4. Check DATABASE_SETUP.md for detailed instructions")
    print("\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
