"""Add opportunity_id to applications table

Revision ID: 2a2390615e09
Revises: 
Create Date: 2026-01-31 19:51:20.561267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a2390615e09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opportunity_id', sa.Integer(), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('unique_student_opportunity_application', ['student_id', 'opportunity_id'])
        batch_op.create_foreign_key(None, 'opportunities', ['opportunity_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_student_opportunity_application', type_='unique')
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('opportunity_id')

    # ### end Alembic commands ###
